### ISSUE TITLE
ModuleNotFoundError: No module named 'keyboard'

### ISSUE THREAD

**Issue by trololol42** [msesjrl/BombPartyBotJKLM#1]
Hello so everything is in the title "ModuleNotFoundError: No module named 'keyboard'"

I have selenium package installed on my computer (and ofc I have python) I tried to ran the "script" through a windows shell with python and python 3.7, nothing work (and ofc when I double click on main.py nothing append).

Btw I have a keyboard pluged in my computer so I have no idea where this error came from.

And your video at the last line on the "README" is not working (Either you deleted it or youtube deleted it).

Thank you for your time.

**Comment by trololol42** [comment]
Well nevermind I saw the readme and I'm just dumb

**Comment by msesjrl** [comment]
There is a new YouTube video now if anyone is having any more trouble 😃
