### ISSUE TITLE
Dict

### ISSUE THREAD

**Issue by trololol42** [msesjrl/BombPartyBotJKLM#2]
Does this have a fr dict ? If no, how can I had one ?

**Comment by trololol42** [comment]
Cause I've tried to upload my own fr dict with the name "web2" with no extention, but it didn't work. witch can be found here 
https://raw.githubusercontent.com/trololol42/fr-dict/main/dict.txt

**Comment by msesjrl** [comment]
You can add any file you want for the program to choose from. 
![image](https://user-images.githubusercontent.com/38955706/128351414-cbdc57f1-4539-4741-8244-a17b44acdb84.png)
just change the "\web2" to the file name (remember the extension) for example "\frenchWords.txt"

**Comment by msesjrl** [comment]
The web2 file currently only has English words
