### ISSUE TITLE
Sometimes the bot automatically stops mid game

### ISSUE THREAD

**Issue by D3FAU4T** [msesjrl/BombPartyBotJKLM#6]
In the CMD terminal, it shows this and stops working

DevTools listening on ws://127.0.0.1:52401/devtools/browser/a1ae5837-e8ce-4b5f-a03b-38d92df15da1
[8712:12656:0831/202432.058:ERROR:device_event_log_impl.cc(214)] [20:24:32.058] Bluetooth: bluetooth_adapter_winrt.cc:1073 Getting Default Adapter failed.
[6116:10340:0831/202624.968:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled

**Comment by msesjrl** [comment]
What do you mean it stops work what happens?

**Comment by D3FAU4T** [comment]
It runs perfectly fine but sometimes randomly stops working. Like, bot's turn, he inputted the word but after one round of the arrow, when his turn comes back again, he dont type anything. Just like the code stopped working. Not every time but this occurs randomly sometimes

**Comment by msesjrl** [comment]
Are you using the default words list?

**Comment by D3FAU4T** [comment]
Yes the default word list "web2" with no extension

**Comment by DO-Ui** [comment]
I think this is likely an issue with the chromedriver and not the code, I encountered this issue before but the code had no issues.

**Comment by DO-Ui** [comment]
try updating your chrome driver

**Comment by D3FAU4T** [comment]
Thanks for helping. The chrome driver that came up with the bot went old
when an update on chrome browser happened. So, the code is fine. You can
close the issue now and I will keep in mind to update the chrome driver
everytime an update in chrome browser happens.
